allowBuilds:
  esbuild: true
  "@github/copilot": true
  koffi: true
minimumReleaseAgeExclude:
  - '@github/copilot-darwin-arm64@1.0.79'
  - '@github/copilot-darwin-x64@1.0.79'
  - '@github/copilot-linux-arm64@1.0.79'
  - '@github/copilot-linux-x64@1.0.79'
  - '@github/copilot-linuxmusl-arm64@1.0.79'
  - '@github/copilot-linuxmusl-x64@1.0.79'
  - '@github/copilot-win32-arm64@1.0.79'
  - '@github/copilot-win32-x64@1.0.79'
  - '@github/copilot@1.0.79'
